# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageSort/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 498)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(51, 51, 51, 255), stop:1 rgba(25, 25, 25, 255));\n"
"color: #fff;")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.controls = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls.sizePolicy().hasHeightForWidth())
        self.controls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.controls.setFont(font)
        self.controls.setTitle("")
        self.controls.setObjectName("controls")
        self.sortOptions = QtWidgets.QGroupBox(self.controls)
        self.sortOptions.setGeometry(QtCore.QRect(10, 40, 241, 61))
        self.sortOptions.setTitle("")
        self.sortOptions.setObjectName("sortOptions")
        self.hue = QtWidgets.QRadioButton(self.sortOptions)
        self.hue.setGeometry(QtCore.QRect(0, 20, 102, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.hue.setFont(font)
        self.hue.setObjectName("hue")
        self.saturation = QtWidgets.QRadioButton(self.sortOptions)
        self.saturation.setGeometry(QtCore.QRect(60, 20, 102, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.saturation.setFont(font)
        self.saturation.setObjectName("saturation")
        self.contours = QtWidgets.QRadioButton(self.sortOptions)
        self.contours.setGeometry(QtCore.QRect(160, 20, 102, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.contours.setFont(font)
        self.contours.setObjectName("contours")
        self.sort = QtWidgets.QPushButton(self.controls)
        self.sort.setGeometry(QtCore.QRect(230, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.sort.setFont(font)
        self.sort.setObjectName("sort")
        self.fileOpen = QtWidgets.QPushButton(self.controls)
        self.fileOpen.setGeometry(QtCore.QRect(10, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.fileOpen.setFont(font)
        self.fileOpen.setObjectName("fileOpen")
        self.graphicsView = QtWidgets.QGraphicsView(self.controls)
        self.graphicsView.setGeometry(QtCore.QRect(360, 0, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.dirOpen = QtWidgets.QPushButton(self.controls)
        self.dirOpen.setGeometry(QtCore.QRect(120, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dirOpen.setFont(font)
        self.dirOpen.setObjectName("dirOpen")
        self.gridLayout.addWidget(self.controls, 0, 0, 1, 1)
        self.results = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results.sizePolicy().hasHeightForWidth())
        self.results.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.results.setFont(font)
        self.results.setObjectName("results")
        self.gridLayout.addWidget(self.results, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 653, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hue.setText(_translate("MainWindow", "Hue"))
        self.saturation.setText(_translate("MainWindow", "Saturation"))
        self.contours.setText(_translate("MainWindow", "Contours"))
        self.sort.setText(_translate("MainWindow", "Sort"))
        self.fileOpen.setText(_translate("MainWindow", "Open File"))
        self.dirOpen.setText(_translate("MainWindow", "Open Directory"))

